import React, { useState, useEffect } from 'react';
import { db } from '../firebaseConfig';
import { ref, onValue } from 'firebase/database';

export default function RecordsView({ targetDate }) {
  const [attendance, setAttendance] = useState({});

  const getLocalDate = () => {
    const now = new Date();
    const offset = now.getTimezoneOffset() * 60000;
    return (new Date(now - offset)).toISOString().split('T')[0];
  };

  const displayDate = targetDate || getLocalDate();

  const reportHeaderDate = new Date(displayDate).toLocaleDateString('en-US', { 
    month: '2-digit', day: '2-digit', year: '2-digit' 
  }).replace(/\//g, '-');

  useEffect(() => {
    const attendanceRef = ref(db, `attendance/${displayDate}`);
    
    const unsubscribe = onValue(attendanceRef, (snap) => {
      setAttendance(snap.val() || {});
    });

    return () => unsubscribe();
  }, [displayDate]);

  // --- UPDATED SORTING LOGIC ---
  const studentRecords = Object.values(attendance)
    .filter(r => r.role?.toLowerCase() === 'student')
    .sort((a, b) => {
      // Create Date objects from timeIn strings for comparison
      const timeA = new Date(a.timeIn || 0).getTime();
      const timeB = new Date(b.timeIn || 0).getTime();
      return timeA - timeB; // Change to 'timeB - timeA' if you want the newest at the top
    });

  const formatTime = (timeStr) => {
    if (!timeStr || timeStr === "--") return '-- : --';
    try {
      if (typeof timeStr === 'string' && (timeStr.includes('AM') || timeStr.includes('PM'))) {
        return timeStr.toUpperCase();
      }
      const date = new Date(timeStr);
      if (isNaN(date.getTime())) return timeStr;
      return date.toLocaleTimeString('en-US', { 
        hour: '2-digit', minute: '2-digit', hour12: true 
      }).toUpperCase();
    } catch (e) {
      return timeStr;
    }
  };

  return (
    <div className="record-sheet">
      <div className="report-header-centered" style={{ textAlign: 'center', marginBottom: '20px' }}>
        <h1 className="report-main-title" style={{ fontSize: '1.8rem', fontWeight: '800', margin: '0' }}>ACCESS LOG REPORT</h1>
        <div className="report-meta-info" style={{ marginTop: '10px', fontSize: '0.9rem' }}>
          <p style={{ margin: '2px 0' }}><strong>School Name:</strong> Trinidad Municipal College</p>
          <p style={{ margin: '2px 0' }}><strong>Date Generated:</strong> {new Date().toLocaleDateString('en-GB')}</p>
        </div>
      </div>

      <div className="record-header">
        <h2 className="record-label">STUDENT RECORDS :</h2>
        <h3 className="record-date-display">{reportHeaderDate}</h3>
      </div>

      <table className="official-record-table">
        <thead>
          <tr>
            <th style={{ width: '8%' }}>NO.</th>
            <th style={{ width: '40%' }}>FULL NAME</th>
            <th style={{ width: '15%' }}>ROLE</th>
            <th style={{ width: '18.5%' }}>TIME IN</th>
            <th style={{ width: '18.5%' }}>TIME OUT</th>
          </tr>
        </thead>
        <tbody>
          {studentRecords.length > 0 ? (
            studentRecords.map((r, i) => (
              <tr key={i}>
                <td className="text-center">{(i + 1).toString().padStart(2, '0')}</td>
                <td className="name-cell" style={{ textTransform: 'uppercase' }}>{r.name}</td>
                <td className="text-center">Student</td>
                <td className="text-center">{formatTime(r.timeIn)}</td>
                <td className="text-center">{formatTime(r.timeOut)}</td>
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan="5" className="empty-state">No student records found for this date.</td>
            </tr>
          )}
        </tbody>
      </table>

      <div className="record-summary-line" style={{ marginTop: '20px', borderTop: '1px solid #000', paddingTop: '10px' }}>
        <p style={{ margin: '5px 0' }}><strong>TOTAL NUMBER OF RECORDS:</strong> {studentRecords.length.toString().padStart(2, '0')}</p>
        <p style={{ margin: '5px 0', fontStyle: 'italic', fontSize: '0.85rem' }}>Generated by: Access Log Administrator</p>
      </div>
    </div>
  );
}